version: "3.7"
services:
  dashboard:
    image: grafana/grafana-oss
    user: 963:20000
    container_name: dashboard
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/serverconfig:/var/lib/grafana
    ports:
      - 80:3000
    depends_on:
      - influxdb
    healthcheck:
      test: [ "CMD-SHELL", "ls -l /proc/1/fd | grep -q socket" ]
      interval: 33s
      timeout: 1s
      retries: 10
    networks:
      - grafana
      - influxdb

  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - 9093:9093
    volumes:
      - ./system/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    deploy:
      mode: global

  covid_exporter:
    build:
      args:
        UID: 965
        GID: 8008
        user: "sicko"
      context: ./covidexporter
    container_name: covid_exporter
    environment:
      TZ: "Canada/Eastern"
      NODE_ENV: production
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_ORG: none
      INFLUX_BUCKET: telegraf/autogen
      AUTH_TOKEN: yrcTkKl6fRkq4pbPDls7NChs3byFHzegObt-YvuVv6cTH3xgNbwDD10WX1nUr7L1do8AMGjMHys8-ic_feznMQ==
    depends_on:
      - influxdb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    command: "npm rum start"
    healthcheck: 
      #test: [ "CMD-SHELL", "ps -ef | egrep -q '[0-9]{2} node' && curl -s 'http://influxdb:8086/query?db=telegraf&q=%3BSELECT%20first(%22confirmed%22)%20FROM%20%22jhu_covid%22%20WHERE%20(%22country%22%20%3D%20%27Canada%27)%20AND%20(%22province%22%20%3D%20%27quebec%27)%20AND%20time%20%3E%3D%20now()%20-%201d%20GROUP%20BY%20time(1d)%2C%22province%22fill(null)&epoch=ms' | grep -q quebec" ]
      test: [ "CMD-SHELL", "ps -ef | egrep -q '[0-9]{2} node' " ]
      interval: 30s
      timeout: 1s
      retries: 10
    networks:
      - influxdb

  influxdb:
    image: arm64v8/influxdb:latest
    user: 964:8008
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://influxdb:8086/metrics | wc -c"  ]
      interval: 30s
      timeout: 1s
      retries: 10
    restart: unless-stopped
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_DB=telegraf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./influxdb:/var/lib/influxdb
      - ./influxdb2:/var/lib/influxdb2
    networks:
      - influxdb

  influxdb-admin:
    image: chronograf
    ports:
      - 8888:8888
    networks:
      - influxdb

  telegraf:
    build:
      args:
        UID: 965
        GID: 8008
        user: "sicko"
      context: ./system/telegraf
    user: "20400:970"   #971 docker group
    restart: unless-stopped
    container_name: telegraf
    environment:
      - OST_PROC=/host/proc
    command: telegraf
    cap_add:
      - SYS_TIME
    depends_on:
      - influxdb
    volumes:
      - ./system/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
    networks:
      - influxdb

  ddwrt_exporter:
    build:
      args:
        UID: 965
        GID: 8008
        user: "sicko"
      context: ./system/ddwrtSnmpToStatsD
    user: "20400:8008"   #967 docker group
    restart: unless-stopped
    container_name: ddwrtExporter
    command: "npm start"
    secrets:
      - ddwrtauthkey
    environment:
      TZ: "Canada/Eastern"
      NODE_ENV: production
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_ORG: none
      DDWRT_ADDR: "192.168.1.1"
      INFLUX_BUCKET: telegraf/autogen
      PULL_PERIOD_MS: 60000
      AUTH_TOKEN: 
    depends_on:
      - influxdb
    networks:
      - influxdb

  nodered:
    build:
      context: ./system/nodered
    restart: unless-stopped
    container_name: nodered
    command: "npm add ./custom-nodes/logcatter; xnpm start"
    ports:
      - 1880:1880
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - ./system/nodered/nodereddata:/data
      - noderedsshkeys:/usr/src/node-red/.ssh
    networks:
      - influxdb


networks:
  grafana:
  influxdb:

secrets:
  ddwrtauthkey:
    file: ./ddwrtauthkey

volumes:
  noderedsshkeys:
